### ISSUE TITLE
stripe-checkout component does not render

### ISSUE THREAD

**Issue by weihao** [vue-stripe/vue-stripe-checkout-nuxt-demo#14]
Followed README step-by-step and got a blank page:

![Screenshot 2021-04-11 223007](https://user-images.githubusercontent.com/31719556/114333152-a2a0d580-9b15-11eb-86d1-dc77bce55bc8.png)
![Screenshot 2021-04-11 223041](https://user-images.githubusercontent.com/31719556/114333154-a3396c00-9b15-11eb-8760-b9b46a1bfb6e.png)

**Comment by weihao** [comment]
SSR demo does not work. I also built the demo project on local and it does not render as well.

**Comment by weihao** [comment]
@jofftiquez Could you take a look at this issue when you are free?

https://vue-stripe-checkout-nuxt-demo.herokuapp.com/ SSR demo does not seem to be working
![vue](https://user-images.githubusercontent.com/31719556/114486355-b747a100-9bdb-11eb-92a0-6487795b05c8.PNG)

**Comment by jofftiquez** [comment]
@weihao thank you for telling me. I'll take a look. In the meantime please use the repo for vuestripe.com as a reference if you want to implement it in Nuxt. Thanks.

**Comment by hkmsadek** [comment]
nuxt doesn't work

**Comment by jonadeline** [comment]
same here.
I also tried to check the vuestripe.com implementation but no success, i'm not able to render the checkout form as @weihao mentions.  This might be due to NuxtJS version difference (I'm using the latest one and not sure about the one used on vuestripe.com) ?
@jofftiquez  did you have a chance to look at it ? I feel like it's not a big one  
Thank you.

**Comment by jofftiquez** [comment]
Hi, I will update this repo. I'll let you know when it's done. Thanks.

**Comment by jofftiquez** [comment]
Hello all @jonadeline @hkmsadek @weihao 

The repo has been updated. New versions of the demo are also available now in:

Firebase (Static): https://vue-stripe-checkout-nuxt-demo.web.app/
Heroku (SSR): https://vue-stripe-checkout-nuxt-demo.herokuapp.com/

Please let me know if there's anything that I missed. I will close this for now. Thank you again for using my plugin. <3
